name: hci_hda_chiu_suharta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.17.5
  fluttertoast: ^8.2.5
  line_awesome_flutter: ^3.0.1
  ionicons: ^0.2.2
  logger: ^2.3.0
  flutter_localization: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-BlackItalic.ttf

